services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: unipath_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: unipath
      DB_PORT: "5432"
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unipath_user -d unipath"]
      interval: 5s
      timeout: 35s
      retries: 5

  api:
    # image: nbottari9/unipath-api:latest
    build: ./api
    container_name: unipath-api
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: "postgres://unipath_user:admin@postgres:5432/unipath"
      POSTGRES_HOST: "postgres://postgres-db"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "unipath_user"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "unipath"
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:4000/health"]
      interval: 5s
      timeout: 35s
      retries: 5

  frontend:
    # image: nbottari9/unipath-frontend:latest
    build: ./web
    container_name: frontend
    restart: on-failure
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  postgres_data:
